### ISSUE TITLE
defsystem compilation error in slime

### ISSUE THREAD

**Issue by habamax** [fukamachi/cl-project#30]
For a freshly created project 
```
(cl-project:make-project #p"~/projects/common-lisp/hello-world2/")
```

I try to compile `asd` file with `C-c C-k` and I have the error:

```
../hello-world2/hello-world2.asd:16:53:
  read-error: 
    READ error during COMPILE-FILE:
    
      The function COMMON-LISP-USER::SUBPATHNAME is undefined.
    
      (in form starting at line: 5, column: 0, position: 54)
```

Now if I remove :long-description and try to recompile:

```
Execution of a form compiled with errors.
Form:
  ((:MODULE "src" :COMPONENTS ((:FILE "hello-world2"))))
Compile-time error:
  illegal function call
```

And if I add `asdf:` to the `defsystem` I can actually compile `asd` file:
```
(asdf:defsystem "hello-world2"
  :version "0.1.0"
  :author ""
  :license ""
  :depends-on ()
  :components ((:module "src"
                :components
                ((:file "hello-world2"))))
  :description ""
  :in-order-to ((test-op (test-op "hello-world2-test"))))
```

Do I miss some crucial configuration for my sbcl?

**Comment by cestrand** [comment]
I have the same problem.

**Comment by fukamachi** [comment]
ASD files are not intended to be compiled or to be loaded in that way. Use `asdf:load-system`.

**Comment by b3ast-t** [comment]
@fukamachi according to https://lispcookbook.github.io/cl-cookbook/systems.html it should be possible. This also led me to think that C-c C-k should be possible.
Regarding your statement that `.asd` files are not meant to be compiled or loaded via C-c C-k is there some official source of information on this?
