### ISSUE TITLE
How to specify projects base path?

### ISSUE THREAD

**Issue by Hellseher** [fukamachi/cl-project#32]
Hi,

For example in Slime REPL I want to create a new project in my $HOME/Projects directory but my REPL is not running there. Is there any default projects directory path variable like Qucklisp has `ql:*local-project-directories*`

**Comment by fukamachi** [comment]
How about `cl:*default-pathname-defaults*` ?
2018年9月26日(水) 5:32 Sharlatan <notifications@github.com>:
